#!/bin/bash

# A Bash script used to build the Apptainer container generated by srlab-bioinformatics-container.def.
# The script is specifically designed to be executed on the UW Hyak HPC, Klone.
#
# Output is an Apptainer container called: srlab-bioinformatics-container-<commit_hash>.sif
# <commit_hash> is the most recent git commit hash from srlab-bioinformatics-container.def

# Set input definition file
input_definition="srlab-bioinformatics-container.def"

# Set output directory
output_dir="/gscratch/srlab/containers"


# Pull the most recent changes from the repository
echo "Pulling the latest changes from git repository..."
git pull || { echo "Error: git pull failed."; exit 1; }

# Capture most recent commit hash
build_commit=$(git log --follow --oneline -- "${input_definition}" | awk 'NR == 1 {print $1}')
if [ -z "${build_commit}" ]; then
  echo "Error: Unable to retrieve git commit hash."
  exit 1
fi

# Container filename
container_basename="${input_definition%%.*}-${build_commit}"


# Check if build already exists
if [ -f "${output_dir}/${container_basename}.sif" ]; then
  echo "Build ${output_dir}/${container_basename}.sif already exists. Exiting."
  exit 1
fi

# Build the sandbox and print output to the console in real-time
echo "Building sandbox for ${container_basename}..."
apptainer build --sandbox --fakeroot /tmp/"${container_basename}".sandbox "./${input_definition}" 2>&1 | tee sandbox_build.log
if [ "${PIPESTATUS[0]}" -ne 0 ]; then
  echo "Error: Sandbox build failed."
  exit 1
fi

# Build the final .sif image and print output to the console in real-time
echo "Building .sif image for ${container_basename}..."
apptainer build /tmp/"${container_basename}".sif /tmp/"${container_basename}".sandbox 2>&1 | tee "${container_basename}"-build.log
if [ "${PIPESTATUS[0]}" -ne 0 ]; then
  echo "Error: .sif image build failed."
  exit 1
fi

# Move the final .sif image to the output directory
echo "Moving ${container_basename}.sif to ${output_dir}..."
mv /tmp/"${container_basename}".sif "${output_dir}" || { echo "Error: Failed to move .sif file to output directory."; exit 1; }

echo "Build complete: ${output_dir}/${container_basename}.sif"
exit 0
