#!/bin/bash

# A Bash script used to build the Apptainer container generated by srlab-bioinformatics-container.def.
# The script is specifically designed to be executed on the UW Hyak HPC, Klone.
# 
# Output is an Apptainer container called: srlab-bioinformatics-container-<commit_hash>.sif
# <commit_hash> is the most recent git commit hash from srlab-bioinformatics-container.def

###### Set input definition file
input_definition="srlab-bioinformatics-container.def"

###### Set output directory ######
output_dir="/gscratch/srlab/containers"

###### Set container filename #######

# Capture most recent commit hash
build_commit=$(git log --follow --oneline -- ${input_definition} \
| awk 'NR == 1 {print $1}')

# Container filename
container_basename="${input_definition%%.*}-${build_commit}"

###### Build container #######

# Pull most recent commit
git pull

# Check to see if build already exists
if [ -f !${output_dir}/"${container_basename}"-"${build_commit}".sif ]; then
  apptainer build \
  --sandbox \
  --fakeroot \
  /tmp/"${container_basename}".sandbox \
  ./"${container_basename}".def \
  && \
  apptainer build /tmp/"${container_basename}"-"${build_commit}".sif /tmp/"${container_basename}".sandbox \
  && \
  mv /tmp/"${container_basename}"-"${build_commit}".sif ${output_dir}
else
  printf "%s\n" "Build ${output_dir}/${container_basename}-${build_commit}.sif already exists." "Exiting script."
  exit 1
fi