---
title: "20180628_roadrunner_oly_TEs_repeatmasker"
output: html_notebook
---



```{bash}
echo "TODAY'S DATE:"
date
echo "------------"
echo ""
#Display operating system info
lsb_release -a
echo ""
echo "------------"
echo "HOSTNAME: "; hostname 
echo ""
echo "------------"
echo "Computer Specs:"
echo ""
lscpu
echo ""
echo "------------"
echo ""
echo "Memory Specs"
echo ""
free -mh
```

---

#### Make output directory and copy updated Olympia oyster genome assembly

#### Assembly details are here: https://github.com/RobertsLab/resources/wiki/Genomic-Resources#genome-1

```{bash}
mkdir /home/sam/analyses/20180628_oly_repeatmasker

time \
cp /mnt/owl/halfshell/genomic-databank/Olurida_v081.fa /home/sam/analyses/20180628_oly_repeatmasker

```

```{bash}
ls -l /home/sam/analyses/20180628_oly_repeatmasker
```

```{bash}
mv /home/sam/analyses/20180628_oly_repeatmasker/Olurida_v081.fa /home/sam/data/oly_assemblies

ls -lhtr /home/sam/data/oly_assemblies
```

---

#### Make output directories

```{bash}
mv /home/sam/analyses/20180628_oly_repeatmasker /home/sam/analyses/20180628_oly_repeatmasker_defaults
mkdir /home/sam/analyses/20180628_oly_repeatmasker_Cgigas
mkdir /home/sam/analyses/20180628_oly_repeatmasker_Cvirginica
mkdir /home/sam/analyses/20180628_oly_repeatmasker_Olurida

```

---

#### Run RepeatMasker with default setting and following options:

-par 15 : Use 15 CPU threads

-gff : Create GFF output file (in addition to default files)

-excln : Adjusts output table calculations to exclude sequence runs of >=25Ns. Useful for draft genome assemblies.

-1> : Send stdout to file instead of printing to notebook.

-2> : Send stderr to file instead of printing to notebook.


```{bash}
wd="/home/sam/analyses/20180628_oly_repeatmasker_defaults"
cd "$wd"
time \
/home/shared/RepeatMasker-4.0.7/RepeatMasker \
/home/sam/data/oly_assemblies/Olurida_v081.fa \
-par 15 \
-gff \
-excln \
1> "$wd"/stdout.out \
2> "$wd"/stderr.err
sed '/^Subject:/ s/ / repeatmasker defaults JOB COMPLETE/' ~/.default-subject.mail | msmtp "$EMAIL"
```


---

#### Run RepeatMasker with Crassostrea gigas species setting and following options:

-species "crassostrea gigas" : Sets species to Crassostrea gigas

-par 15 : Use 15 CPU threads

-gff : Create GFF output file (in addition to default files)

-excln : Adjusts output table calculations to exclude sequence runs of >=25Ns. Useful for draft genome assemblies.

-1> : Send stdout to file instead of printing to notebook.

-2> : Send stderr to file instead of printing to notebook.



```{bash}
wd="/home/sam/analyses/20180628_oly_repeatmasker_Cgigas"
cd "$wd"
time \
/home/shared/RepeatMasker-4.0.7/RepeatMasker \
/home/sam/data/oly_assemblies/Olurida_v081.fa \
-species "crassostrea gigas" \
-par 15 \
-gff \
-excln \
1> "$wd"/stdout.out \
2> "$wd"/stderr.err
sed '/^Subject:/ s/ / repeatmasker gigas JOB COMPLETE/' ~/.default-subject.mail | msmtp "$EMAIL"
```


---

#### Run RepeatMasker with Crassostrea gigas species setting and following options:

-species "crassostrea gigas" : Sets species to Crassostrea gigas

-par 15 : Use 15 CPU threads

-gff : Create GFF output file (in addition to default files)

-excln : Adjusts output table calculations to exclude sequence runs of >=25Ns. Useful for draft genome assemblies.

-1> : Send stdout to file instead of printing to notebook.

-2> : Send stderr to file instead of printing to notebook.

```{bash}
wd="/home/sam/analyses/20180628_oly_repeatmasker_Cvirginica"
cd "$wd"
time \
/home/shared/RepeatMasker-4.0.7/RepeatMasker \
/home/sam/data/oly_assemblies/Olurida_v081.fa \
-species "crassostrea virginica" \
-par 15 \
-gff \
-excln \
1> "$wd"/stdout.out \
2> "$wd"/stderr.err
sed '/^Subject:/ s/ / repeatmasker virginica JOB COMPLETE/' ~/.default-subject.mail | msmtp "$EMAIL"
```


---

#### Run RepeatMasker with Crassostrea gigas species setting and following options:

-species "crassostrea gigas" : Sets species to Crassostrea gigas

-par 15 : Use 15 CPU threads

-gff : Create GFF output file (in addition to default files)

-excln : Adjusts output table calculations to exclude sequence runs of >=25Ns. Useful for draft genome assemblies.

-1> : Send stdout to file instead of printing to notebook.

-2> : Send stderr to file instead of printing to notebook.

```{bash}
wd="/home/sam/analyses/20180628_oly_repeatmasker_Olurida"
cd "$wd"
time \
/home/shared/RepeatMasker-4.0.7/RepeatMasker \
/home/sam/data/oly_assemblies/Olurida_v081.fa \
-species "crassostrea virginica" \
-par 15 \
-gff \
-excln \
1> "$wd"/stdout.out \
2> "$wd"/stderr.err
sed '/^Subject:/ s/ / repeatmasker lurida JOB COMPLETE/' ~/.default-subject.mail | msmtp "$EMAIL"
```

