---
title: "gene_annotation"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Run BLASTx
```{bash blastx}
#####################################################################
## CHANGE VARIABLES IN THIS SECTION TO MATCH YOUR SYSTEM
# Set programs and database paths
{
programs_dir=~/programs
blast_dir=${programs_dir}
blastdbs_dir=~/data/databases/blastdbs/
blastx="${blast_dir}"/diamond
blastdb="${blastdbs_dir}"/uniprot_sprot_20200123/uniprot_sprot.dmnd

# Set BLASTx parameters
evalue="1E-20"
threads=48
max_target_seqs=1
max_hsps=1
output_format=6

# Set desired BLAST verion here.
# Check https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/LATEST/
# to determine if newer version is available.
blast_version=2.12.0
} >> .rvars
#####################################################################

```

### Load necessary libraries

```{r libraries, message = FALSE}
library(GSEABase)
library(tidyverse)
```


### Download Generic GOslim from Gene Ontology Consortium to proper GSEAbase directory

```{r Download_GOslim_file}

# Find install location for GSEAbase
gseabase_location <- find.package("GSEABase")

# Set GOslim URL
goslims_url <- "http://current.geneontology.org/ontology/subsets/goslim_generic.obo"

# Set file name of target GO slim file
goslims <- "goslim_generic.obo"

# Set the download file location for the GOslim file
# Needs to be in the "extdata" directory where GSEAbase is installed
outfile_dest <- file.path(gseabase_location, "extdata", goslims, fsep = "/")

# Download the generic GOslim file in the GSEAbase "extdata" directory
download.file(url = goslims_url,
              destfile = outfile_dest)
```
